Latency tool rules
luxteam/jobs_test_streaming_sdk pull request #181
Opened 2022-09-01 22:27 UTC by mrKeepo

2022-09-05 07:48 UTC, Speedwag00n requested changes

2022-09-05 07:48 UTC, Speedwag00n commented on jobs/Scripts/clientTests.py
> +            analyze_latency_tool_logs(json_content, latency_log_path)
Нужно добавить проверку, что latency_log_path не None

2022-09-05 07:48 UTC, Speedwag00n commented on jobs/Scripts/analyzeLogs.py
> +        if latency_tool_results and json_content["test_status"] != "skipped":
json_content["test_status"] != "skipped" можно убрать, т.к. для скипнутого кейса данная функция вызываться не будет в принципе

2022-09-05 07:48 UTC, Speedwag00n commented on jobs/Scripts/analyzeLogs.py
> +            json_content["test_status"] != "passed"
Похоже, что это забыли удалить

2022-09-05 07:48 UTC, Speedwag00n requested changes
Также ждем новых тачек, чтобы запустить эти изменений, после мерджим

2022-09-05 22:24 UTC, mrKeepo commented on jobs/Scripts/analyzeLogs.py
> +            json_content["test_status"] != "passed"
Это я думал об одном, а написал другое. Тут подразумевается, что мы в любом случае выставляем кейсу passed, после чего обрабатываем latency tool правилами, выставляя статусы

2022-09-06 06:06 UTC, Speedwag00n approved these changes
Ждем машин

2022-09-14 15:41 UTC, merged