Psergeev/streaming sdk traces collection
luxteam/jobs_test_streaming_sdk pull request #333
Opened 2023-04-13 14:46 UTC by mark-rom

Add possibility to collect Streaming SDK traces and show them in report

collect_streaming_traces=True
Отработка win-win:
https://rpr.cis.luxoft.com/job/StreamingSDKManual/1956/
Отработка win-A:
https://rpr.cis.luxoft.com/job/StreamingSDKManual/1963/
-------
collect_streaming_traces=False
Отработка win-win:
https://rpr.cis.luxoft.com/job/StreamingSDKManual/1967/
Отработка win-A:
https://rpr.cis.luxoft.com/job/StreamingSDKManual/1966/

2023-04-13 15:55 UTC, Speedwag00n requested changes

2023-04-13 15:55 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/simpleRender.py
> +                    archive_dir_content(args, case)
Нужно поправить отступ

2023-04-13 15:55 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/simpleRenderAndroid.py
> +                    archive_dir_content(args, case)
Нужно поправить отступ

2023-04-13 15:55 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/utils.py
> +        enable_dump = json_file['Display']['EnableDump']
Нужно проверять, что в имеющемся конфиге присутствует ключ Display и ключ EnableDump в словаре по нему. Их наличие не гарантируется

2023-04-13 15:55 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/utils.py
> +def enabe_collecting_traces(
Функция не переименована, даже комментарий остался

2023-04-13 15:55 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/utils.py
> +import zipapp
Неиспользуемый импорт

2023-04-14 07:09 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/simpleRender.py
> +                    archive_dir_content(args, case)
done

2023-04-14 07:09 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/simpleRenderAndroid.py
> +                    archive_dir_content(args, case)
done

2023-04-14 07:10 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/utils.py
> +        enable_dump = json_file['Display']['EnableDump']
сделал цикл для проверки

2023-04-14 07:10 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/utils.py
> +def enabe_collecting_traces(
done

2023-04-14 07:10 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/utils.py
> +import zipapp
done

2023-04-18 12:29 UTC, Speedwag00n requested changes

2023-04-18 12:29 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/utils.py
> +                return
Если одного из ключей нет в конфиге, нужно его добавить
Сейчас же, если одного из ключей нет, выполнение функции будет прервано

2023-04-19 06:15 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/utils.py
> +                return
done

2023-04-21 06:35 UTC, Speedwag00n approved these changes

2023-04-26 06:28 UTC, merged