Psergeev/ingame resolution change
luxteam/jobs_test_streaming_sdk pull request #336
Opened 2023-04-20 11:45 UTC by mark-rom

Add ability to chose resolution of test applications

dota-win: https://rpr.cis.luxoft.com/job/StreamingSDKManual/2029/

pubg-win: https://rpr.cis.luxoft.com/job/StreamingSDKManual/2030

valley-win: https://rpr.cis.luxoft.com/job/StreamingSDKManual/2031

lol-win: https://rpr.cis.luxoft.com/job/StreamingSDKManual/2022/

heaven-win: https://rpr.cis.luxoft.com/job/StreamingSDKManual/2026

pubg-andr: https://rpr.cis.luxoft.com/job/StreamingSDKManual/2038/

lol-andr: https://rpr.cis.luxoft.com/job/StreamingSDKManual/2036/

heaven-andr: https://rpr.cis.luxoft.com/job/StreamingSDKManual/2039

2023-04-20 12:00 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/android_actions.py
> +            if self.args.ingame_resolution:
Давай вынесем это в отдельную функцию. В server_actions.py похожая логика

2023-04-20 12:00 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/android_actions.py
> +                if any([x in self.game_name for x in config_res_games]):
Давай сделаем функцию для проверки игра это или бенчмарк. Например, is_game

2023-04-20 12:09 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/games_actions.py
> +        if 'lol' in game_name:
Лучше через elif

2023-04-20 12:09 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/games_actions.py
> +        if 'pubg' in game_name:
Лучше через elif

2023-04-20 12:12 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/games_actions.py
> +        main_logger.error(f"Failed to set resolution. Exception: {e}")
Давай логгировать еще и resolution, который не удалось выбрать

2023-04-20 12:14 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/games_actions.py
> +            if resolution:
Давай проверять, что, если выбран default resolution, игнорируем выставление resolution, т.к. оно каждый раз само сбрасывается

2023-04-20 14:41 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/android_actions.py
> +                    self.logger.info('Default resolution 1920x1080 has been set')
done

2023-04-20 14:41 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/android_actions.py
> +            if self.args.ingame_resolution:
done

2023-04-20 14:41 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/android_actions.py
> +                if any([x in self.game_name for x in config_res_games]):
done

2023-04-20 14:41 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/games_actions.py
> +        if 'pubg' in game_name:
done

2023-04-20 14:41 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/games_actions.py
> +        main_logger.error(f"Failed to set resolution. Exception: {e}")
done

2023-04-20 14:41 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/games_actions.py
> +            if resolution:
done

2023-04-24 11:35 UTC, Speedwag00n requested changes
Нужно добавить номый параметр во все windows/android XML файлы

2023-04-25 06:29 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/scripts/run_ubuntu_server.sh
> +python3.9 ../jobs_launcher/executeTests.py --test_filter $TESTS_FILTER --file_filter $FILE_FILTER --tests_root ../jobs --work_root ../Work/Results --work_dir StreamingSDK --cmd_variables clientTool "
removed

2023-04-26 06:16 UTC, Speedwag00n approved these changes

2023-04-26 07:05 UTC, merged