Psergeev/refactor streaming opening
luxteam/jobs_test_streaming_sdk pull request #365
Opened 2023-05-15 08:32 UTC by mark-rom

Task:
https://luxproject.luxoft.com/jira/browse/STVCIS-3792

Builds:

RS
https://rpr.cis.luxoft.com/job/StreamingSDKManual/2367/
FS
https://rpr.cis.luxoft.com/job/StreamingSDKManual/2381/

2023-05-18 15:06 UTC, Speedwag00n requested changes

2023-05-18 15:06 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/run_programs/run_streaming.py
> +            for setting in ("codec", "enable_hq_scaler", "algorithm"):
Для enable_hq_scaler должна вызываться функция _set_hq_scaler

2023-05-19 06:25 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/run_programs/run_streaming.py
> +                    self.locate_on_screen(self.elements.CONNECT.build_path())
Я не согласен. В строке 218 отлавливается любой exception после чего запускается новый оборот цикла.

Запусти код ниже в любом интерпретаторе, он отработает 3 витка цикла
`def some_func(a):
    if a != 3:
        raise Exception
    else:
        print("some_func executed correctly")

for i in range(1, 4):
    try:
        some_func(i)
    except Exception:
        print(f"try #{i}")
        continue`

2023-05-19 07:53 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/run_programs/run_streaming.py
> +                    self.locate_on_screen(self.elements.CONNECT.build_path())
По итогу доработал вот до такой конструкции, чтобы не крутить цикл лишние разы, если уже нашлась кнопка (добавлю break после функции).
`Python
def some_func(a):
    if a != 2:
        raise Exception
    else:
        print("some_func executed correctly")

for i in range(1, 4):
    try:
        some_func(i)
        break
    except Exception:
        print(f"try #{i}")
        continue`

2023-05-19 13:35 UTC, mark-rom commented
Оба стриминга работают на смоках (после решения проблем с мердж конфликтом), чуть позже еще поставлю коннекшен для fs

2023-05-22 07:46 UTC, Speedwag00n commented
Will run more tests after weeklys

2023-05-31 11:09 UTC, closed without merging