Psergeev/config log comparison
luxteam/jobs_test_streaming_sdk pull request #392
Opened 2023-08-17 15:08 UTC by mark-rom

Jira task
https://luxproject.luxoft.com/jira/browse/STVCIS-4058

Jenkins Builds:

2023-08-23 12:53 UTC, Speedwag00n requested changes

2023-08-23 12:53 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rule_impl/config_rules.py
> +                            break
```suggestion
                if setting_value != 0:
                    # 0 means free framerate, no need to check
                    if (self.config["Application"]["CapFPS"] or self.config["Application"]["DiplayCapture"] == "DD") and setting_value > 60:
                        # if CapFPS is True or DiplayCapture == "DD" and Framerate value in config > 60
                        # it is not an error if 60 <= framerate in logs < framerate in config
                        for value in metric_values:
                            if not 60 <= value <= setting_value:
                                error_message = f"Config problem: {config_keys} is {setting_value}, but value in logs is {value}"
                                main_logger.debug(f"{error_message}")
                                break
                    else:
                        # common rule
                        for value in metric_values:
                            if not setting_value - 2 <= value <= setting_value + 2:
                                error_message = f"Config problem: {config_keys} is {setting_value}, but value in logs is {value}"
                                main_logger.debug(f"{error_message}")
                                break
```

2023-08-23 12:53 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rule_impl/config_rules.py
> +                            # add "and diff != 0"?
Временный комментарий

2023-08-23 12:53 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rule_impl/config_rules.py
> +                    for idx, bitrate in enumerate(metric_values[1:], 1):
Добавь на будущее краткий комментарий, что здесь дифф, высчитаннный между соседними значениями метрик, и значением шага из конфига

2023-08-23 12:53 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rule_impl/config_rules.py
> +                        # сделать математическое округление diff
Временный комментарий

2023-08-23 12:53 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rule_impl/config_rules.py
> +                if config_keys in ("Display-VideoSliceCount", "Display-VideoSliceOutput") and self.config["Display"]["VideoSliceOutput"] is not True:
```suggestion
                if config_keys in ("Display-VideoSliceCount", "Display-VideoSliceOutput") and self.config["Display"]["VideoSliceOutput"] is False:
```

2023-08-23 12:53 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rule_impl/config_rules.py
> +                    # default is not always HEVC, need consultation with QA
Нужно спросить у QA

2023-08-23 13:56 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rule_impl/config_rules.py
> +        return math.ceil(expoN) / 10 ** decimals
А можем к тому же удобству чтения отнести?

2023-08-23 14:22 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rule_impl/config_rules.py
> +                for idx, date in enumerate(timestamp_value[1:], 1):
done

2023-08-23 14:22 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rule_impl/config_rules.py
> +                        main_logger.debug(f"{error_message}")
done

2023-08-23 14:22 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rule_impl/config_rules.py
> +                        error_message = f"Config problem: {config_keys} is {setting_value}, but value in logs is {value}"
done

2023-08-23 14:22 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rule_impl/config_rules.py
> +                        error_message = f"Config problem: {config_keys} is {setting_value}, but value in logs is {value}"
done

2023-08-23 14:23 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rule_impl/config_rules.py
> +                self.json_content["message"].append(error_message)
done

2023-08-23 14:23 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rule_impl/config_rules.py
> +                    for idx, bitrate in enumerate(metric_values[1:], 1):
done

2023-08-23 14:23 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rule_impl/config_rules.py
> +                        # сделать математическое округление diff
removed

2023-08-23 14:23 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rule_impl/config_rules.py
> +                    # default is not always HEVC, need consultation with QA
add new logic

2023-08-24 11:48 UTC, Speedwag00n approved these changes

2023-09-15 10:26 UTC, merged