Psergeev/parsec impl
luxteam/jobs_test_streaming_sdk pull request #397
Opened 2023-09-14 16:11 UTC by mark-rom

Task:
https://luxproject.luxoft.com/jira/browse/STVCIS-4133

Builds:
https://rpr.cis.luxoft.com/job/DevJobs/job/StreamingSDKManual/78/
https://rpr.cis.luxoft.com/job/DevJobs/job/StreamingSDKManual/79/

Implemented work with Parsec streaming (opening, server-client connection, log collection, closing), and Smoke cases

2023-09-15 06:50 UTC, Speedwag00n requested changes
В репорте Client keys и Server keys пустые (колонка Info)

Также проверь на Smoke группах, что с этими изменениями работают FS и RS

2023-09-15 06:50 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/run_programs/run_program.py
> +        coords = self.locate_on_screen_depricated(
Оставь FIXME комментарий

2023-09-15 06:50 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rules_processor.py
> +            if "PRSC" in case["case"]:
Логичней было бы весь цикл for занести под такое условие. Так в каждой итерации будет проверяться это условие

2023-09-15 06:50 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/run_programs/run_streaming.py
> +        if self.args.execution_type != "server":
Так условие чуть более явно
```suggestion
        if self.args.execution_type == "client":
```

2023-09-15 06:50 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/server_actions.py
> +        if self.args.streaming_type == StreamingType.PARSEC:
Я бы ожидал увидеть этот блок кода в RunParsec

2023-09-15 06:50 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/server_actions.py
> +            sleep(5)
Лучше не делать задержку, а отправлять с клиента сообщение, что все ок, сервер пусть его ожидает

2023-09-15 06:50 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/server_actions.py
> +            make_window_active(window)
Проверь на большой группе с HeavenDX9, будет ли все ок работать
Раньше точно была проблема, что, если много раз (5-10 раз) сворачивать окно бенчмарка в фулл скрин режиме, оно подвисает
Решали это просто переходом в оконный режим (иначе никак, баг бенчмарка)
https://github.com/luxteam/jobs_test_streaming_sdk/blob/1386f00c2ab8cd44b872a7cbac3aaae2493769a3/drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/android_actions.py#L80

2023-09-15 06:50 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/streaming_actions.py
> +            close_streaming_server_process(process)
Эта функция вызывается на клиенте, т.к. нет никаких доп. проверок. Это ожидаемо?

2023-09-15 07:50 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rules_processor.py
> +            if "PRSC" in case["case"]:
Не очень понимаю про итерации.
Сейчас при наличии в названии кейса "PRSC" мы дропаем выполнение цикла, потому что текущие GENERAL_RULES не подходят для Парсека (то же для любых других правил). Как только у нас появятся правила для него, мы сможем этот и другие такие моменты с rules переписать так, как будет удобно

2023-09-15 07:50 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/run_programs/run_streaming.py
> +        if self.args.execution_type != "server":
Это условие в том числе для нескольких клиентов, если такое нам не нужно, то я поправлю

2023-09-15 07:52 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/server_actions.py
> +            make_window_active(window)
Если ты заглядывал в репорт, то мог видеть, что уже на втором кейсе бенчмарк виснет. Думаю нет смысла прогонять большую группу, лучше сразу сделать оконный режим

2023-09-15 07:53 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/streaming_actions.py
> +            close_streaming_server_process(process)
Эта функция вызывается на обеих машинах, потому что не стоит под условием, как и оба Popen перед ней

2023-09-15 07:55 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/server_actions.py
> +            make_window_active(window)
Да, давай так и сделаем

2023-09-15 15:02 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/server_actions.py
> +        if self.args.streaming_type == StreamingType.PARSEC:
done

2023-09-15 15:02 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/server_actions.py
> +            sleep(5)
done

2023-09-15 15:02 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/server_actions.py
> +            make_window_active(window)
done

2023-09-15 15:02 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/streaming_actions.py
> +            close_streaming_server_process(process)
deleted

2023-09-18 10:30 UTC, Speedwag00n approved these changes

2023-09-20 07:39 UTC, merged