Pseergeev/streaming tools overview report
luxteam/jobs_test_streaming_sdk pull request #408
Opened 2023-10-17 14:45 UTC by mark-rom

2023-11-13 15:01 UTC, Speedwag00n requested changes

2023-11-14 08:43 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/streaming_actions.py
> +            # psutil.Popen(["taskkill", "/f", "/im", "moonlight.exe"])
done

2023-11-14 08:43 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/client_actions.py
> +            params["arguments_line"] = "1000 800" if action.__name__ == "Move" else "1"
done

2023-11-23 07:07 UTC, Speedwag00n requested changes

2023-11-23 07:07 UTC, Speedwag00n commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/utils.py
> +        main_logger.debug(f"total execution time of the script {(end - start).total_seconds()}")
Удали эти изменения

2023-11-23 08:48 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/client_actions.py
> +            self.activate_ssdk_window()
уже удалена

2023-11-23 09:15 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/utils.py
> +        main_logger.debug(f"total execution time of the script {(end - start).total_seconds()}")
done

2023-11-23 09:15 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/server_actions.py
> +                    sleep(40)
done

2023-11-23 09:15 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/server_actions.py
> +                should_collect_traces = (self.args.collect_traces == "AfterTests" and self.args.streaming_type == StreamingType.SDK)
done

2023-11-23 09:15 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/server_actions.py
> +            self.logger.debug(f"track used memory is type {type(self.params['args'].track_used_memory)} and is {self.params['args'].track_used_memory}")
done

2023-11-23 09:15 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/rules/rules_processor.py
> +                main_logger.debug("General rules don't apply for Gamestream")
done

2023-11-23 09:16 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/client_actions.py
> +                    should_collect_traces = (self.args.collect_traces == "AfterTests" and self.args.streaming_type == StreamingType.SDK)
done

2023-11-23 09:16 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/client_actions.py
> +            #     make_window_active(hwnd)
done

2023-11-23 09:16 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/client_actions.py
> +            # add logic to unfold parsec window if latancy
done

2023-11-23 09:16 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/client_actions.py
> +                        sleep(40)
done

2023-11-23 09:16 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/client_actions.py
> +                    should_collect_traces = (self.args.collect_traces == "AfterTests" and self.args.streaming_type == StreamingType.SDK)
done

2023-11-23 09:16 UTC, mark-rom commented on drivers/amf/stable/tools/tests/StreamingSDKTests/jobs/Scripts/client_actions.py
> +            should_collect_traces = (self.args.collect_traces == "AfterTests" and self.args.streaming_type == StreamingType.SDK)
done

2023-11-24 07:13 UTC, Speedwag00n approved these changes

2023-11-24 07:13 UTC, merged